waypoints:
    - point:
        x: 128.373
        y: -63.6425
        z: 0.00928216
        function: run
    - point:
        x: 142.316
        y: -63.1747
        z: 0.00928216
    - point:
        x: 153.057
        y: -62.3556
        z: 0.00928597
    - point:
        x: 167.491
        y: -60.3761
        z: 4.01916e-05
        function: suspend
    - point:
        x: 180.154
        y: -58.3386
        z: 0.00461178
